const BASE_SIZE = 10;

const CAMERA_POSITIONS = [
  [BASE_SIZE, BASE_SIZE, BASE_SIZE],

  [-BASE_SIZE, -BASE_SIZE, 0.2 * BASE_SIZE],

  [0.8 * BASE_SIZE, 0.7 * BASE_SIZE, -0.4 * BASE_SIZE]
];

export { BASE_SIZE, CAMERA_POSITIONS };
